---
# Inventario para maquina de desenvolvimento controlando a VM via tunel SSH.
# Ex.: ssh -L 2222:localhost:22 usuario@IP_DA_VM
all:
  children:
    homolog:
      hosts:
        homolog-vm:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: cezar
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    prod:
      hosts:
        prod-vm:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: cezar
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
