-- Schema base (H2 em modo PostgreSQL + PostgreSQL)

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    login VARCHAR(50) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    situacao VARCHAR(20) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_usuario_login ON usuario (login);

CREATE TABLE IF NOT EXISTS lancamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(200) NOT NULL,
    data_lancamento DATE NOT NULL,
    valor NUMERIC(10, 2) NOT NULL,
    tipo_lancamento VARCHAR(20) NOT NULL,
    situacao VARCHAR(20) NOT NULL
);
